version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: prog_db
    environment:
      POSTGRES_DB: prog_bd
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      # Persistance des données
      - pgdata:/var/lib/postgresql/data
      # Script d'init (ton init.sql dans le même dossier que ce fichier)
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

volumes:
  pgdata:
